### ISSUE TITLE
具体实现要求

### ISSUE THREAD

**Issue by RicterZ** [Sharuru/MessageBoard-with-Web.py#1]
功能：
- 列出所有留言
- 删除留言
- 添加留言

URL：
- `/`，对应`IndexHandler`，接受`GET`方法，列出留言
- `/newPost`，对应`NewPostHandler`，只接受`POST`方法，发表留言
- `/delPost`，对应`DelPostHandler`，只接受`POST`方法，删除留言

其中：
`IndexHandler`显示留言时要同时显示留言的时间，例如：

| 姓名 | 邮箱 | 时间 | 内容 |
| --- | --- | --- | --- |
| Ricter | i@moeloli.me | 2014/7/28 15:04 | j酱是菊苣 |
| Sharuru | i@0w0.re | 2014/7/28 15:08 | j酱是菊苣 |

`NewPostHandler`接受姓名、邮箱、内容这三个参数。
`DelPostHandler`无需接受参数，但是必须用`POST`方法（也就是一个表单，method为`POST`，无需用web.form）。

**Comment by RicterZ** [comment]
如果有任何问题，回复这条 issue 就好。

**Comment by Sharuru** [comment]
功能实现完成。
使用Jinja2重构HTML部分，见issue #2
