### ISSUE TITLE
更好的安全性

### ISSUE THREAD

**Issue by Sharuru** [Sharuru/MessageBoard-with-Web.py#8]
Cookies Hash记录

**Comment by Sharuru** [comment]
验证思路：
大概就是在登陆时采用某种方法算出hash然后记录进库，每次管理操作时查看本地cookies记录hash与库中记录hash是否吻合。
数据库记录hash超时检测：
这个应该要新写一个功能，在每次管理操作时先对自己记录的hash进行检测，超时则删除hash记录，用户登录时则因为没有吻合hash记录导致管理操作失败

**Comment by RicterZ** [comment]
随机生成hash对应到用户，酱

发自我的 iPad

**Comment by Sharuru** [comment]
This issue is out of date.
